[theme]
primaryColor = "#315B85"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202D3A"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false
